defaults:
  model_names:
    - cardiffnlp/twitter-roberta-base-sentiment-latest
    - finiteautomata/bertweet-base-sentiment-analysis
    - martin-ha/toxic-comment-model
    - facebook/roberta-hate-speech-dynabench-r4-target
  targeted: True
  target_class: 0
  confidence_threshold: 0.9
  log_level: DEBUG
  query_budget: 100
  rand_init_text: True
  attack_params: {}
  initial_text: "! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! !"
  num_repetitions: 1

experiments:
  - attack_name: character_roulette_black_box_random_char
    num_repetitions: 10
  - attack_name: character_roulette_black_box_random_word
  - attack_name: character_roulette_white_box
    num_repetitions: 2
    rand_init_text: False
    query_budget: 1000
  - attack_name: pez
    rand_init_text: True
    attack_params:
      filter_token_ids_method: by_glove_score
      word_refs: [food, cheese, drink, eat, fruit, vegetable, meat, lettuce, apple]
  - attack_name: gcg
    rand_init_text: False
    num_repetitions: 5
