metrics:
  - score
  - perplexity
  - entropy

defaults:
  models:
    - name: cardiffnlp/twitter-roberta-base-sentiment-latest
    - name: martin-ha/toxic-comment-model
  targeted: False
  confidence_threshold: 0
  query_budget: 1
  num_repetitions: 100

experiments:
  - attack_name: baseline
    rand_init_text: True
