metrics:
  - name: score
  - name: perplexity
  - name: entropy

defaults:
  attack_recipe:
    targeted: False
    confidence_threshold: 0
    query_budget: 1
    attack_name: baseline
  num_repetitions: 100

experiments:
  - name: baseline_rand_init
    models:
      - name: cardiffnlp/twitter-roberta-base-sentiment-latest
      - name: martin-ha/toxic-comment-model
  - name: baseline_cola
    models:
      - name: cardiffnlp/twitter-roberta-base-sentiment-latest
    dataset:
      name: nyu-mll/glue
      subset: cola
