defaults:
  model_names:
    - cardiffnlp/twitter-roberta-base-sentiment-latest
    - finiteautomata/bertweet-base-sentiment-analysis
  targeted: True
  target_class: 0
  confidence_threshold: 0.5
  log_level: INFO
  query_budget: 1
  num_repetitions: 500

experiments:
  - attack_name: baseline
    rand_init_text: True
