defaults:
  model_names:
    - cardiffnlp/twitter-roberta-base-sentiment-latest
    - finiteautomata/bertweet-base-sentiment-analysis
    - - martin-ha/toxic-comment-model
    - facebook/roberta-hate-speech-dynabench-r4-target
  targeted: False
  confidence_threshold: 0
  query_budget: 1
  num_repetitions: 250

experiments:
  - attack_name: baseline
    rand_init_text: True
