metrics:
  - name: score
    metric_params:
      include_skipped_results: True
  - name: perplexity
  - name: entropy
    metric_params:
      include_skipped_results: True

defaults:
  models:
    - name: cardiffnlp/twitter-roberta-base-sentiment-latest
    - name: martin-ha/toxic-comment-model
  targeted: False
  confidence_threshold: 0
  query_budget: 1
  num_repetitions: 100

experiments:
  - attack_name: baseline
    rand_init_text: True
  - attack_name: baseline
    models:
      - name: cardiffnlp/twitter-roberta-base-sentiment-latest
    dataset:
      name: nyu-mll/glue
      subset: cola
