metrics:
  - name: entropy
  - name: perplexity
  - name: queries
  - name: success_rate
  - name: time
  - name: score

defaults:
  attack_recipe:
    attack_name: pez
    confidence_threshold: 0.9
    query_budget: 1000
    targeted: True
  num_repetitions: 100
  input_text: "aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa"

experiments:
  - name: pez_bounded_by_glove_score_happy
    models:
      - name: cardiffnlp/twitter-roberta-base-sentiment-latest
        target_classes: [0]
    attack_recipe:
      attack_params:
        filter_token_ids_method: by_glove_score
        word_refs: [happy]
  - name: pez_bounded_by_glove_score_curses
    models:
      - name: cardiffnlp/twitter-roberta-base-sentiment-latest
        target_classes: [2]
    attack_recipe:
      attack_params:
        filter_token_ids_method: by_glove_score
        word_refs: [fuck, shit, nazi]
  - name: pez_bounded_by_glove_score_animals
    models:
      - name: cardiffnlp/twitter-roberta-base-sentiment-latest
        target_classes: [0]
    attack_recipe:
      attack_params:
        filter_token_ids_method: by_glove_score
        word_refs: [dog, cat, rabbit, mouse, lion, ant, animal]
  - name: pez_bounded_by_glove_score_food
    models:
      - name: cardiffnlp/twitter-roberta-base-sentiment-latest
        target_classes: [0]
    attack_recipe:
      attack_params:
        filter_token_ids_method: by_glove_score
        word_refs: [food, drink, meat, pasta, wine, cheese]
  - name: pez_bounded_by_glove_score_nature
    models:
      - name: cardiffnlp/twitter-roberta-base-sentiment-latest
        target_classes: [0]
    attack_recipe:
      attack_params:
        filter_token_ids_method: by_glove_score
        word_refs: [green, forest, flower, earth, sun]
  - name: pez_bounded_by_glove_score_signs
    models:
      - name: cardiffnlp/twitter-roberta-base-sentiment-latest
        target_classes: [2]
    attack_recipe:
      attack_params:
        filter_token_ids_method: by_glove_score
        word_refs: [")", "(", "#" , "}" , "{"]
