metrics:
  - entropy
  - perplexity
  - queries
  - success_rate
  - time
  - score

defaults:
  models:
    - name: cardiffnlp/twitter-roberta-base-sentiment-latest
      target_classes: [0, 2]
    - name: finiteautomata/bertweet-base-sentiment-analysis
      target_classes: [0, 2]
  targeted: True
  confidence_threshold: 0.9
  query_budget: 500
  initial_text: "aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa"
  num_repetitions: 100

experiments:
  # PEZ
  - attack_name: pez
    rand_init_text: False
    attack_params:
      filter_token_ids_method: by_target_class
  - attack_name: pez
    rand_init_text: False
    attack_params:
      filter_token_ids_method: by_random_tokens
      num_random_tokens: 50

  # GCG
  - attack_name: gcg
    rand_init_text: False
    attack_params:
      filter_token_ids_method: by_target_class
  - attack_name: gcg
    rand_init_text: False
    attack_params:
      filter_token_ids_method: by_random_tokens
      num_random_tokens: 50

  # PEZ
  - attack_name: pez
    rand_init_text: False
    target_classes: [0]
    attack_params:
      filter_token_ids_method: by_glove_score
      word_refs: [happy]
  - attack_name: pez
    rand_init_text: False
    target_classes: [2]
    attack_params:
      filter_token_ids_method: by_glove_score
      word_refs: [fruit]
  - attack_name: pez
    rand_init_text: False
    target_classes: [2]
    attack_params:
      filter_token_ids_method: by_glove_score
      word_refs: [fuck, shit, nazi]
  - attack_name: pez
    rand_init_text: False
    target_classes: [0]
    attack_params:
      filter_token_ids_method: by_glove_score
      word_refs: [dog, cat, rabbit, mouse, lion, ant, animal]
  - attack_name: pez
    rand_init_text: False
    target_classes: [0]
    attack_params:
      filter_token_ids_method: by_glove_score
      word_refs: [food, drink, meat, pasta, wine, cheese]

  # GCG
  - attack_name: gcg
    rand_init_text: False
    target_classes: [0]
    attack_params:
      filter_token_ids_method: by_glove_score
      word_refs: [happy]
  - attack_name: gcg
    rand_init_text: False
    target_classes: [2]
    attack_params:
      filter_token_ids_method: by_glove_score
      word_refs: [fruit]
  - attack_name: gcg
    rand_init_text: False
    target_classes: [2]
    attack_params:
      filter_token_ids_method: by_glove_score
      word_refs: [fuck, shit, nazi]
  - attack_name: gcg
    rand_init_text: False
    target_classes: [0]
    attack_params:
      filter_token_ids_method: by_glove_score
      word_refs: [dog, cat, rabbit, mouse, lion, ant, animal]
  - attack_name: gcg
    rand_init_text: False
    target_classes: [0]
    attack_params:
      filter_token_ids_method: by_glove_score
      word_refs: [food, drink, meat, pasta, wine, cheese]
