metrics:
  - name: entropy
  - name: perplexity
  - name: queries
  - name: success_rate
  - name: time
  - name: score



defaults:
  models:
    - name: cardiffnlp/twitter-roberta-base-sentiment-latest
      target_classes: [0, 2]
  attack_recipe:
    attack_name: gcg
    confidence_threshold: 0.9
    query_budget: 1000
    targeted: True
    attack_params:
      filter_token_ids_method: by_random_tokens
      num_random_tokens: 50
  num_repetitions: 100


experiments:
  - name: gcg_bounded_by_random_tokens_rand_init
  - name: gcg_bounded_by_random_tokens
    input_text: "aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa"
