metrics:
  - name: entropy
  - name: perplexity
  - name: queries
  - name: success_rate
  - name: time
  - name: score

defaults:
  targeted: True
  confidence_threshold: 0.9
  query_budget: 750
  initial_text: "aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa"
  num_repetitions: 100

experiments:
  - attack_name: pez
    rand_init_text: False
    models:
    - name: martin-ha/toxic-comment-model
      target_classes: [ 1 ]
    attack_params:
      - lr: 2
  - attack_name: pez
    rand_init_text: True
    models:
      - name: martin-ha/toxic-comment-model
        target_classes: [1]
    attack_params:
      - lr: 2
  - attack_name: pez
    rand_init_text: False
    models:
      - name: cardiffnlp/twitter-roberta-base-sentiment-latest
        target_classes: [0, 2]
  - attack_name: pez
    rand_init_text: True
    models:
      - name: cardiffnlp/twitter-roberta-base-sentiment-latest
        target_classes: [0, 2]
