metrics:
  - name: entropy
  - name: perplexity
  - name: queries
  - name: success_rate
  - name: time
  - name: score

defaults:
  models:
    - name: cardiffnlp/twitter-roberta-base-sentiment-latest
      target_classes: [0, 2]
    - name: martin-ha/toxic-comment-model
      target_classes: [1]
  targeted: True
  confidence_threshold: 0.9
  query_budget: 500
  initial_text: "aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa"
  num_repetitions: 100

experiments:
  - attack_name: pez
    rand_init_text: True
  - attack_name: pez
    rand_init_text: False
