metrics:
  - name: entropy
  - name: perplexity
  - name: queries
  - name: success_rate
  - name: time
  - name: score

defaults:
  models:
    - name: cardiffnlp/twitter-roberta-base-sentiment-latest
      target_classes: [0, 2]
    - name: martin-ha/toxic-comment-model
      target_classes: [1]
  attack_recipe:
    attack_name: pez
    confidence_threshold: 0.9
    query_budget: 750
    targeted: True
  num_repetitions: 100

experiments:
  - name: pez_unbounded_rand_init
  - name: pez_unbounded
    input_text: "aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa"
