defaults:
  model_names:
    - cardiffnlp/twitter-roberta-base-sentiment-latest
    - finiteautomata/bertweet-base-sentiment-analysis
    - martin-ha/toxic-comment-model
    - facebook/roberta-hate-speech-dynabench-r4-target
  targeted: True
  target_classes: [0]
  confidence_threshold: 0.9
  log_level: DEBUG
  query_budget: 1000
  initial_text: "! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! !"
  num_repetitions: 500

experiments:
  - attack_name: character_roulette_black_box_random_char
    rand_init_text: True
  - attack_name: character_roulette_black_box_random_char
    rand_init_text: False
  - attack_name: character_roulette_black_box_random_word
    rand_init_text: True
  - attack_name: character_roulette_black_box_random_word
    rand_init_text: False
  - attack_name: character_roulette_white_box
    rand_init_text: True
  - attack_name: character_roulette_white_box
    rand_init_text: False
  - attack_name: pez
    rand_init_text: True
  - attack_name: pez
    rand_init_text: False
  - attack_name: gcg
    rand_init_text: True
  - attack_name: gcg
    rand_init_text: False
