DEFAULT_CACHE_DIR = "cache"
DEFAULT_PREFIXES = ["This is ", ""]
BERT_FILTER_DEFAULT_BATCH_SIZE = 4096
TARGET_CLASS_FILTER_DEFAULT_BATCH_SIZE = 1024
DEFAULT_RANDOM_SENTENCE_LENGTH = 20
ROOT_LOGGER_NAME = "alphabet_soup"
